package com.github.milomarten.taisha_rangers2.dice;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum Gem {
      Agate("Agate"),
      Agate_Geode("Agate Geode"),
      Alexandrite("Alexandrite"),
      Almandine_Garnet("Almandine Garnet"),
      Amazonite("Amazonite"),
      Amethyst("Amethyst"),
      Ametrine("Ametrine"),
      Ammolite("Ammolite"),
      Andalusite("Andalusite"),
      Apatite("Apatite"),
      Aquamarine("Aquamarine"),
      Aventurine("Aventurine"),
      Axinite("Axinite"),
      Beryl("Beryl"),
      Bloodstone("Bloodstone"),
      Boulder_Opal("Boulder Opal"),
      Calcite("Calcite"),
      Carnelian("Carnelian"),
      Cassiterite("Cassiterite"),
      Charoite("Charoite"),
      Chrome_Diopside("Chrome Diopside"),
      Citrine("Citrine"),
      Clinohumite("Clinohumite"),
      Diamond("Diamond"),
      Emerald("Emerald"),
      Enstatite("Enstatite"),
      Fire_Agate("Fire Agate"),
      Fire_Opal("Fire Opal"),
      Fluorite("Fluorite"),
      Hematite("Hematite"),
      Hiddenite("Hiddenite"),
      Howlite("Howlite"),
      Iolite("Iolite"),
      Jasper("Jasper"),
      Kyanite("Kyanite"),
      Lapis_Lazuli("Lapis Lazuli"),
      Malachite("Malachite"),
      Mali_Garnet("Mali Garnet"),
      Melanite("Melanite"),
      Moldavite("Moldavite"),
      Moonstone("Moonstone"),
      Morganite("Morganite"),
      Moss_Opal("Moss Opal"),
      Nuummite("Nuummite"),
      Obsidian("Obsidian"),
      Onyx("Onyx"),
      Opal("Opal"),
      Peridot("Peridot"),
      Prehnite("Prehnite"),
      Pyrope_Garnet("Pyrope Garnet"),
      Quartz("Quartz"),
      Rainbow_Moonstone("Rainbow Moonstone"),
      Rainbow_Pyrite("Rainbow Pyrite"),
      Rhodochrosite("Rhodochrosite"),
      Rhodolite_Garnet("Rhodolite Garnet"),
      Rhodonite("Rhodonite"),
      Rose_Quartz("Rose Quartz"),
      Ruby("Ruby"),
      Sapphire("Sapphire"),
      Scapolite("Scapolite"),
      Seraphinite("Seraphinite"),
      Serpentine("Serpentine"),
      Snowflake_Obsidian("Snowflake Obsidian"),
      Sodalite("Sodalite"),
      Sphalerite("Sphalerite"),
      Sphene("Sphene"),
      Spinel("Spinel"),
      Star_Diopside("Star Diopside"),
      Star_Garnet("Star Garnet"),
      Star_Ruby("Star Ruby"),
      Star_Sapphire("Star Sapphire"),
      Sugilite("Sugilite"),
      Sunstone("Sunstone"),
      Tanzanite("Tanzanite"),
      Tigers_Eye("Tiger's Eye"),
      Topaz("Topaz"),
      Tourmaline("Tourmaline"),
      Turquoise("Turquoise"),
      Verdite("Verdite"),
      Zircon("Zircon");

      private final String name;
}
